상품 리스트 page 구현중
wecode-bootcamp-korea/27-1st-Brokurly-frontend pull request #2
Opened 2021-11-30 06:03 UTC by Globalkmaria

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 상품 리스트(메인 화면) 레이아웃 구현
- 중분류 클릭시 해당 중분류로 이동
- 정렬 버튼에 따른 상품들 정렬
- 장바구니 버튼 클릭 시 장바구니 Modal 띄우기
- 상품 담았을 때 장바구니 업데이트 하기
- 상품 클릭시 상품 상세 페이지로 이동
- 
<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2021-12-01 05:42 UTC, younuk23 requested changes
상품 리스트 page -> 상품 리스트페이지 레이아웃, 필터링 기능 추가
제목에서 명확히 드러나게 해주는게 좋습니다!

성장포인트도 잘 고민하셔서 잘 작성해주셨네요!!
구현사항 설명도 잘 작성해주셨는데 조금 더 잘 하자면 작성시 조금 더 어떻게(HOW)에 초점을 맞춰서 작성해주세요!!
구현사항을 잘 적으면서 내가 어떻게 구현했는지 스스로 이해도를 점검해볼 수 있으며 나중에 내가 어떤 고민을 하고 문제를 어떻게 해결했는지 점검해보면서 스스로를 회고해볼 수 있는 좋은 자산이 됩니다!

2021-12-01 05:42 UTC, younuk23 commented on src/pages/ProductList/ProducListContent/ContentHeader/ContentHeader.js
> +  const TOTAL = 6;
- 이 값 같은 경우에는 매 rendering 마다 새롭게 선언되고 할당될 필요는 없어보입니다.
- 이런 상수데이터를  함수형 컴포넌트 본문 안에서 선언하게 되면 rendering이 일어날때 마다 매번 데이터를 만들고 변수에 값을 할당하는 연산이 일어나게 됩니다.
- 따라서 성능에 악영향을 미칠 수 있습니다.
- 컴포넌트가 사용하는 데이터라고 컴포넌트 안에만 위치할 필요는 없습니다
- 통상 이런 상수데이터같은 경우에는 여러 컴포넌트에서 동시에 사용하는 데이터라면 별도 파일로 분리하거나,이 컴포넌트 안에서만 사용하는 데이터라면 컴포넌트 하단에 작성해줍니다

2021-12-01 05:42 UTC, younuk23 commented on src/pages/ProductList/ProducListContent/ContentHeader/ContentHeader.js
> +    setCurCategoty(`${curCategoty}${id}`);
현재 선택된 카테고리가 무엇인지에 대한 내용에 대한 값인데 curCatgory, sortCheck 두개의 값으로 분리되어 있는 것 같네요,
이렇게 되면 추후 문제가 생겼을 때 두개의 값 중 어디서 문제가 생긴지 확인해봐야 하는 소요가 생깁니다.

curCategory 하나로만 숫자로 관리하는것이 좋아보인다고 생각되는데 혹시 따로 분리하신 이유가 있을까요?

2021-12-01 05:42 UTC, younuk23 commented on src/pages/ProductList/ProducListContent/ContentHeader/ContentHeader.js
> +    setCurCategoty(`${curCategoty}${id}`);
categoty -> category 
cur -> current
네이밍 하실 때 축약어는 지양하는게 좋습니다!

2021-12-01 05:42 UTC, younuk23 commented on src/pages/ProductList/ProducListContent/ContentHeader/ContentHeader.scss
> +  .sortBtns {
btns부분에 따로 스타일링을 부여할 것이 아니라면 클래스네임도 부여할 필요가 없습니다!

2021-12-01 05:42 UTC, younuk23 commented on src/pages/ProductList/ProducListContent/ProducListContent.js
> +import Products from './Products/Products';
push 하시고 나서 sider 가 달아주는 코멘트도 확인하고 해결해주세요!

2021-12-01 05:42 UTC, younuk23 commented on src/pages/ProductList/ProducListContent/ProducListContent.scss
> +@import '../../../styles/common.scss';
common.scss 같은 경우에는 index.js에서 한번만 import 해주면 됩니다.
SPA의 구조를 생각해보면 왜 그런지 알 수 있습니다!

2021-12-01 05:42 UTC, younuk23 commented on src/pages/ProductList/ProducListContent/Products/Product/Product.js
> +    return num.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',');
toLocaleString이라는 메소드도 있습니다 확인해보세요!

2021-12-01 05:42 UTC, younuk23 commented on src/pages/ProductList/ProducListContent/Products/Product/Product.scss
> +  width: 330px;
cursor 보다는 width 속성을 위로 올려주는게 속성순서 컨벤션에 적합해보이네요!

2021-12-01 05:42 UTC, younuk23 commented on src/pages/ProductList/ProducListContent/Products/Products.js
> +import Product from './Product/Product';
import 순서 컨벤션 맞춰주세요!
[Refactoring Checklist](https://www.notion.so/wecode/Westagram-React-Refactoring-Checklist-9422c31c960547f3939fcf7f6c7c0014#4063cbec8bcb4825b740bfb0b42d30db) 확인해서 import 순서 맞춰주세요!

2021-12-01 05:42 UTC, younuk23 commented on src/pages/ProductList/ProductList.js
> +    fetch(`data/productListData${curCategoty}.json`)
절대경로로 적어주세요! 상대경로로 지정하게 되면 path의 depth가 깊어졌을때 원하는대로 public 폴더에 접근을 하지 못합니다!

예시) 상대경로로 작성했을 시
- http://localhost:3000/main => 이경우에는 상대경로로 작성해도 public 폴더로 정상 인식해서 정상동작
- http://localhost:3000/detail/1 => 이경우에는 path의 depth가 깊어져서 상대경로로 지정하게되면 pubilc/detail 폴더안에서 찾으려고 하기 때문에 제대로 동작하지 않음.

2021-12-01 05:42 UTC, younuk23 commented on src/pages/ProductList/ProductList.js
> +      });
```suggestion
      .then(res => res.json())
      .then(res => setProducts(res));
```
arrow function 문법에서 생략 가능한 부분들 잘 확인하면 훨씬 간결하게 작성할 수 있습니다!

2021-12-01 05:42 UTC, younuk23 commented on src/pages/ProductList/ProductListHeader/ProductListHeader.js
> +              categoryCheck === i ? 'category-checked' : ''
👍

2021-12-01 05:42 UTC, younuk23 commented on src/pages/ProductList/ProductListHeader/ProductListHeader.scss
> +    }
```suggestion
    &:hover,  &.category-checked {
      font-weight: 600;
      color: $green;
    }
```

2021-12-01 07:26 UTC, Globalkmaria commented on src/pages/ProductList/ProducListContent/ProducListContent.js
> +import Products from './Products/Products';
넵 바로바로 확인하고 해결하겠습니다!

2021-12-01 07:27 UTC, Globalkmaria commented on src/pages/ProductList/ProducListContent/ContentHeader/ContentHeader.js
> +  const TOTAL = 6;
넵 확인하고 하단에 작성했습니다! 감사합니다!

2021-12-01 07:30 UTC, Globalkmaria commented on src/pages/ProductList/ProducListContent/ContentHeader/ContentHeader.js
> +    setCurCategoty(`${curCategoty}${id}`);
바꾼걸 가져오면 비동기로 문제가 생긴다고 생각해서 분리했는데,
종택님과 이야기해보니 해당 함수가 아닌 ui 부분에서 사용하는거라 비동기 문제가 없다는 부분을 알게되었습니다.
이 부분을 참고해 코드 수정했습니다. 감사합니다!

2021-12-01 07:30 UTC, Globalkmaria commented on src/pages/ProductList/ProducListContent/ContentHeader/ContentHeader.js
> +    setCurCategoty(`${curCategoty}${id}`);
축약어와 오타 수정했습니다!

2021-12-01 07:41 UTC, Globalkmaria commented on src/pages/ProductList/ProducListContent/ContentHeader/ContentHeader.scss
> +  .sortBtns {
넵 수정했습니다! 감사합니다!

2021-12-01 07:45 UTC, Globalkmaria commented on src/pages/ProductList/ProducListContent/ProducListContent.scss
> +@import '../../../styles/common.scss';
common.scss 에 저희는 variables 도 함께 작성해서 모든 scss 에서 불러서 사용했습니다. common 과 variables 를 분리하는게 좋을까요?

2021-12-01 07:54 UTC, Globalkmaria commented on src/pages/ProductList/ProducListContent/Products/Product/Product.js
> +    return num.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',');
날짜에만 사용되는지 알았는데 숫자에도 사용되고 객체 등에도 사용되는 점 확인했습니다. 감사합니다! 참고해서 수정했습니다!

2021-12-01 07:55 UTC, Globalkmaria commented on src/pages/ProductList/ProducListContent/Products/Product/Product.scss
> +  width: 330px;
넵 확인했습니다. 감사합니다! 더 열심히 컨벤션 확인하면서 작성하겠습니다.

2021-12-01 07:58 UTC, Globalkmaria commented on src/pages/ProductList/ProducListContent/Products/Products.js
> +import Product from './Product/Product';
넵 확인했습니다! import 순서 더 꼼꼼히 보겠습니다!

2021-12-01 08:00 UTC, Globalkmaria commented on src/pages/ProductList/ProductList.js
> +    fetch(`data/productListData${curCategoty}.json`)
이부분은 현재 Mock 데이터로 테스트 하는 부분이라 나중에 백엔드랑 실제로 url 받으면 수정하도록하겠습니다! 감사합니다!

2021-12-01 08:01 UTC, Globalkmaria commented on src/pages/ProductList/ProductList.js
> +      });
수정했습니다. 감사합니다!

2021-12-01 08:02 UTC, Globalkmaria commented on src/pages/ProductList/ProductListHeader/ProductListHeader.scss
> +    }
감사합니다!

2021-12-02 05:11 UTC, younuk23 requested changes
마이너한 수정사항들 있습니다. 반영해주세요!

2021-12-02 05:11 UTC, younuk23 commented on src/pages/ProductList/ProducListContent/Products/Product/Product.js
> +        <img src={`./images/${image}`} alt={name} />
```suggestion
        <img src={`/images/${image}`} alt={name} />
```
절대경로로 적어주세요! 상대경로로 지정하게 되면 path의 depth가 깊어졌을때 원하는대로 public 폴더에 접근을 하지 못합니다!

예시) 상대경로로 작성했을 시
- http://localhost:3000/main => 이경우에는 상대경로로 작성해도 public 폴더로 정상 인식해서 정상동작
- http://localhost:3000/detail/1 => 이경우에는 path의 depth가 깊어져서 상대경로로 지정하게되면 pubilc/detail 폴더안에서 찾으려고 하기 때문에 제대로 동작하지 않음.

2021-12-02 05:11 UTC, younuk23 commented on src/pages/ProductList/ProductList.js
> +    fetch(`data/productListData${currentCategory}${currentSort}.json`)
```suggestion
    fetch(`/data/productListData${currentCategory}${currentSort}.json`)
```

2021-12-02 05:11 UTC, younuk23 commented on src/pages/ProductList/ProductList.js
> +  };
상수데이터들이 아직 컴포넌트 안에 남아있네요
코멘트 드린 부분은 전반적으로 확인해주세요!

2021-12-02 07:21 UTC, Globalkmaria commented on src/pages/ProductList/ProducListContent/Products/Product/Product.js
> +        <img src={`./images/${image}`} alt={name} />
네 수정했습니다! 감사합니다!

2021-12-02 07:22 UTC, Globalkmaria commented on src/pages/ProductList/ProductList.js
> +    fetch(`data/productListData${currentCategory}${currentSort}.json`)
네 수정했습니다! 감사합니다!

2021-12-02 08:05 UTC, Globalkmaria commented on src/pages/ProductList/ProductList.js
> +  };
넵 수정했습니다. 감사합니다!

2021-12-03 01:21 UTC, younuk23 commented
컨플릭 해결해주세요!

2021-12-03 01:23 UTC, younuk23 requested changes
컨플릭 해결 되면 머지하겠습니다~!

2021-12-03 01:23 UTC, younuk23 commented on src/pages/ProductList/CartModal/CartModal.js
> +    if (!e.target.closest('.modalContent')) {
contains method를 사용하는게 좀 더 의미상 적합하고, 마크업, className등이 변경됬을 때 좀 더 유연하게 대처할 수 있습니다!
추후 반영해보세요!

2021-12-03 05:44 UTC, Globalkmaria commented on src/pages/ProductList/CartModal/CartModal.js
> +    if (!e.target.closest('.modalContent')) {
넵 수정했습니다 감사합니다!!

2021-12-03 05:45 UTC, Globalkmaria commented on src/pages/ProductList/CartModal/CartModal.js
> +    if (!e.target.closest('.modalContent')) {
넵 수정했습니다 감사합니다!

2021-12-03 08:37 UTC, younuk23 approved these changes
LGTM 👍

2021-12-03 08:37 UTC, merged