[27기 구유진] 상세페이지 레이아웃 구현중
wecode-bootcamp-korea/27-1st-Brokurly-frontend pull request #6
Opened 2021-12-01 06:34 UTC by sodalite1204

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 상품상세페이지에서 상품구매가 가능하게 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2021-12-03 01:36 UTC, younuk23 requested changes
- 구현사항 설명 작성시 조금 더 어떻게(HOW)에 초점을 맞춰서 작성해주세요, 지금은 뭘 했는지에 대한 내용만 있고 어떻게 구현했는지에 대한 부분은 부족한 것 같네요!
- PR 본문에 space 없어서 양식 깨지는 부분이 일부 있습니다 리뷰요청전에 꼼꼼히 확인해주세요!
- push 하시고 나서 sider 가 달아준 코멘트도 확인하고 잘 해결해주세요!!

2021-12-03 01:36 UTC, younuk23 commented on src/pages/ProductDetail/ArticleLeft/ArticleLeft.js
> +function ArticleLeft({ productData }) {
ArticleLeft라는 이름만 보면은 무슨 역할을 하는 컴포넌트인지 알 수가 없어보이네요! 의미가 드러나는 이름을 지어주세요!

2021-12-03 01:36 UTC, younuk23 commented on src/pages/ProductDetail/ArticleRight/ArticleRight.js
> +  const increaseCount = () => setCount(count + 1);
```suggestion
  const increaseCount = () => setCount(prevCount => prevCount + 1);
```
setState  함수안에 인자로 콜백함수를 넣어줄 수 있습니다.
그 콜백함수는 인자로 이전의 state값을 전달받고 return 한 값이 새로운 state가 됩니다!
이전 state 값을 활용해서 새로운 state를 만들때는 위와 같은 방식도 참고해서 적용해보세요!

2021-12-03 01:36 UTC, younuk23 commented on src/pages/ProductDetail/ArticleRight/ArticleRight.scss
> +  .productContainer {
style 부여할 필요 없는 태그한테는 굳이 className도 부여할 필요가 없습니다!

2021-12-03 01:36 UTC, younuk23 commented on src/pages/ProductDetail/ArticleRight/ArticleRight.scss
> +        .purchaseButton {
css selector 끼리 공백주는 것 다 적용해주세요!
사소한 부분이지만 이런것들부터 지켜져야지 가독성이 나빠지지않습니다

2021-12-03 01:36 UTC, younuk23 commented on src/pages/ProductDetail/ProductDetail.js
> +    fetch('http://localhost:3000/data/productDetail.json', {
localhost:3000은 생략가능합니다! 생략하고 절대경로 시작하게 되면 자연스럽게 현재 프로젝트가 실행되고 있는 URL로 인식이 됩니다.
오히려 기입하게 되면 localhost:3000이 아닌 다른 URL에서 프로젝트가 실행될 때 에러가 발생할 수 있습니다

2021-12-03 01:36 UTC, younuk23 commented on src/pages/ProductDetail/ProductDetail.js
> +    fetch('http://localhost:3000/data/productDetail.json', {
```suggestion
    fetch('/data/productDetail.json', {
```

2021-12-03 01:36 UTC, younuk23 commented on src/pages/ProductDetail/ProductDetail.js
> +      method: 'GET',
get method는 기본값으로 생략가능합니다!

2021-12-03 01:36 UTC, younuk23 commented on src/pages/ProductDetail/ArticleRight/DetailTable.js
> +    <div>
필요한 div인가요??

2021-12-03 05:57 UTC, sodalite1204 commented on src/pages/ProductDetail/ArticleLeft/ArticleLeft.js
> +function ArticleLeft({ productData }) {
ProductThumbnail로 변경하여 썸네일이라는것을 알 수 있게 하였습니다!

2021-12-03 06:00 UTC, sodalite1204 commented on src/pages/ProductDetail/ArticleRight/ArticleRight.js
> +  const increaseCount = () => setCount(count + 1);
넵 감사합니다!!

2021-12-03 06:01 UTC, sodalite1204 commented on src/pages/ProductDetail/ArticleRight/ArticleRight.scss
> +  .productContainer {
넵 불필요한 태그의 className 은 삭제하도록 하겠습니다!

2021-12-03 06:02 UTC, sodalite1204 commented on src/pages/ProductDetail/ArticleRight/ArticleRight.scss
> +        .purchaseButton {
넵 셀렉터끼리 공백주는 것 주의하겠습니다.

2021-12-03 06:03 UTC, sodalite1204 commented on src/pages/ProductDetail/ProductDetail.js
> +    fetch('http://localhost:3000/data/productDetail.json', {
포트번호가 변경될 때 에러가 생길 수 있는점 유의해서 변경하도록 하겠습니다!

2021-12-03 06:05 UTC, sodalite1204 commented on src/pages/ProductDetail/ProductDetail.js
> +      method: 'GET',
넵 get일 경우는 생략하도록 하겠습니다.

2021-12-03 06:05 UTC, sodalite1204 commented on src/pages/ProductDetail/ArticleRight/DetailTable.js
> +    <div>
불필요하여서 삭제하였습니다!

2021-12-06 01:25 UTC, merged

2021-12-07 05:53 UTC, yeonuk-hwang commented on src/pages/ProductDetail/ProductInformation/ProductInformation.js
> +  const setPrice = count * price;
naming

2021-12-07 05:53 UTC, yeonuk-hwang commented on src/pages/ProductDetail/ProductInformation/ProductInformation.scss
> +      float: left;
no-float

2021-12-07 05:53 UTC, yeonuk-hwang commented on src/components/Nav/Nav.js
> +                src="http://localhost:3000/images/C.png"
localhost:3000 생략